config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  
  get 'setup' => 'main#setup'
  post 'verify_admin' => 'main#verify_admin', as: :verify_admin

  get 'download_support' => 'main#download_support', as: :download_support
  post 'import' => 'main#import', as: :import
  get 'export' => 'main#export', as: :export

  get 'main/error_500', as: :error_test

  root to: "main#index"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  validate :check_seat_limit

  def to_s; email end

  def check_seat_limit
    if User.count >= License[:seats]
      errors.add(:base, "No more seats available for your license!")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :check_license

  rescue_from Exception do |e|
    `mkdir -p #{Rails.root.join "tmp/exceptions"}`

    text = [e.class.to_s, e.to_s].join("\n") + "\n" +
        Rails.backtrace_cleaner.clean(e.backtrace).join("\n")

    File.open "tmp/exceptions/#{Time.now.to_i}", "w" do |f|
      f.write License.encrypt text
    end

    raise e
  end

  private
    def check_license
      redirect_to "/setup" unless License.present?
    end

    def admin?
      session[:admin]
    end
    helper_method :admin?
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_filter :check_license, only: :setup
  def setup
    render inline: "This should be a response from the app-loader."
  end

  def verify_admin
    if License.verify(params[:license])
      session[:admin] = true
      redirect_to root_path, notice: "Admin verified!"
    else
      redirect_to :back, notice: "Invalid license!"
    end
  end

  def error_500
    raise "error"
  end

  def download_support
    path = "tmp/support-package.esp"

    `tar -czf #{path} tmp/exceptions/*`

    encrypted_package = License.encrypt(File.read(path))
    File.open(path, 'w'){|f| f.write encrypted_package}
    send_file path
  end

  def import
    file = params[:file]

    cmd = "PGPASSWORD=#{db_password} pg_restore --verbose --clean "
    cmd += "--username #{db_username} " if db_username
    cmd += "--host #{db_host} " if db_host
    cmd += "--no-owner --no-acl --dbname #{db_name} #{file.path}"
    system cmd

    redirect_to root_path, notice: "Data import done!"
  end

  def export
    file = Tempfile.new('export')

    cmd ="PGPASSWORD=#{db_password} pg_dump --verbose --clean "
    cmd += "--username #{db_username} " if db_username
    cmd += "--host #{db_host} " if db_host
    cmd += "--no-owner --no-acl --format=c #{db_name} > #{file.path}"
    system cmd

    send_file file.path, filename: "entercom.dump"
  end

  private
    def db_host; ActiveRecord::Base.connection_config[:host] end
    def db_username;  ActiveRecord::Base.connection_config[:username] end
    def db_password;  ActiveRecord::Base.connection_config[:password] || 'none' end
    def db_name; ActiveRecord::Base.connection_config[:database] end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]

  respond_to :html

  def index
    @posts = Post.all
    respond_with(@posts)
  end

  def show
    @post = Post.find(params[:id])
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private
    def set_post
      @post = current_user.posts.find params[:id]
    end

    def post_params
      params.require(:post).permit(:title, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Entercom</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <h1><%= link_to License[:name], root_path %> v<%= APP_VERSION %></h1>
    <h2>Seats: <%= User.count %> / <%= License[:seats] %></h2>

    <% if flash[:notice] %>
      <div style="color:green"><%= flash[:notice] %></div>
    <% end %>

    <p>
      <%= link_to "posts", posts_path %> (<%= Post.count %>)
    </p>

    <% unless user_signed_in? %>
      <%= link_to "sign in", new_user_session_path %>
    <% else %>
      <%= current_user %>
      <%= link_to "sign out", destroy_user_session_path, method: :delete %>
    <% end %>

    <hr>

    <%= yield %>

  </body>
</html>

app/views/main/export.html.erb
<h1>Main#export</h1>
<p>Find me in app/views/main/export.html.erb</p>

app/views/main/import.html.erb
<h1>Main#import</h1>
<p>Find me in app/views/main/import.html.erb</p>

app/views/main/index.html.erb
<% if admin? %>
  <h1>Admin</h1>
  <p>
    <%= link_to "support package", download_support_path %>
  </p>

  <p>
    <%= link_to "export data", export_path %>
  </p>

  <div>
    <h2>Import Data</h2>
    <%= form_tag import_path, multipart: true do %>
      <%= file_field_tag :file %>
      <br>
      <%= submit_tag "Submit" %>
    <% end %>
  </div>

  <p>
    <%= link_to "test error", error_test_path %>
  </p>

  <p>
    <%= link_to "setup", "/setup" %>
  </p>

<% else %>

  <div>
    <h2>Verify Admin</h2>
    <%= form_tag verify_admin_path, multipart: true do %>
      <%= file_field_tag :license %>
      <br>
      <%= submit_tag "Submit" %>
    <% end %>
  </div>

<% end %>

app/views/main/support.html.erb
<h1>Main#support</h1>
<p>Find me in app/views/main/support.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user %></td>
        <td><%= post.title %></td>
        <td><%= link_to 'Show', post %></td>
        <% if post.user == current_user %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<% if @post.user == current_user %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>